shaders:
	f2h 2DShape.vert.shader ../src/shaders.hpp g_2DShape_vertexshader
	f2h 2DShape.frag.shader ../src/shaders.hpp g_2DShape_fragmentshader -a
	echo "//Converted by File2.H!" >> ../src/shaders.hpp
