static const char* g_2DShape_vertexshader = 
	"#version 330 core\n"
	"layout(location=0) in vec4 position;\n"
	"layout(location=1) in uint inColor;\n"
	"layout(location=2) in uint startID;\n"
	"layout(location=2) in uint Flags;\n"
	"\n"
	"\n"
	"//out pos;\n"
	"flat out uint color;\n"
	"flat out uint flags;\n"
	"\n"
	"out vec4 cercelPosX;\n"
	"out vec4 cercelPosY;\n"
	"out float Raduce;\n"
	"out vec4 pos;\n"
	"\n"
	"uniform mat4 u_MVP;\n"
	"\n"
	"\n"
	"\n"
	"void main(){\n"
	"	gl_Position=u_MVP*position;\n"
	"	\n"
	"	if( (Flags & 0xfu) == uint(1)){\n"
	"		/*do somthing potansly cool*/\n"
	"		if((startID)==uint(0)){\n"
	"			cercelPosX.x=position.x;\n"
	"			cercelPosY.x=position.y;\n"
	"		}\n"
	"		else if((startID)==uint(1)){\n"
	"			cercelPosX.y=position.x;\n"
	"			cercelPosY.y=position.y;\n"
	"		}\n"
	"		else if((startID)==uint(2)){\n"
	"			cercelPosX.z=position.x;\n"
	"			cercelPosY.z=position.y;\n"
	"		}\n"
	"		else if((startID)==uint(3)){\n"
	"			cercelPosX.w=position.x;\n"
	"			cercelPosY.w=position.y;\n"
	"		}\n"
	"	}\n"
	"	flags=Flags;\n"
	"	color=inColor;\n"
	"}\n"
	;


/********************************************g_2DShape_fragmentshader***********************************************/
static const char* g_2DShape_fragmentshader = 
	"#version 330 core\n"
	"layout(location=0) out vec4 outcl;\n"
	"\n"
	"\n"
	"flat in uint color;\n"
	"\n"
	"flat in uint flags;\n"
	"\n"
	"in vec4 cercelPosX;\n"
	"in vec4 cercelPosY;\n"
	"in float Raduce;\n"
	"in vec4 pos;\n"
	"\n"
	"\n"
	"\n"
	"/*flags bit structure\n"
	"	|0123|  -> Praticul\n"
	"	|4|     -> texture Enbled\n"
	"	|56789| -> texture slot\n"
	"	|10->31| ->reseved\n"
	"*/\n"
	"\n"
	"\n"
	"\n"
	"void main(){\n"
	"	float r = float((color>>24)&0xffu)/255.0;\n"
	"	float g = float((color>>16)&0xffu)/255.0;\n"
	"	float b = float((color>>8)&0xffu)/255.0;\n"
	"	float a = float(color&0xffu)/255.0;\n"
	"	\n"
	"	vec4 color;\n"
	"		\n"
	"	/*if( (flags & 0xfu) == uint(1)){//a cercul\n"
	"		vec4 cercul;\n"
	"		//if(gl_Position.x > 2.0){}\n"
	"		\n"
	"	}\n"
	"	if( (flags & 0x10u) == uint(1)){// it is a texture\n"
	"		return;	\n"
	"	}*/\n"
	"	\n"
	"	outcl =vec4(r,g,b,a);\n"
	"	\n"
	"}\n"
	;