static const char* g_2DShape_vertexshader = 
	"#version 330 core\n"
	"layout(location=0) in vec4 position;\n"
	"layout(location=1) in uint inColor;\n"
	"layout(location=2) in uint Flags;\n"
	"layout(location=3) in uint startID;\n"
	"\n"
	"//out pos;\n"
	"flat out uint color;\n"
	"flat out uint flags;\n"
	"\n"
	"out vec4 cercelPosX;\n"
	"out vec4 cercelPosY;\n"
	"out vec4 pos;\n"
	"\n"
	"uniform mat4 u_MVP;\n"
	"\n"
	"\n"
	"\n"
	"void main(){\n"
	"	gl_Position=u_MVP*position;\n"
	"	pos=position;\n"
	"	if( (Flags & 0xfu) == uint(1)){\n"
	"		/*do somthing potansly cool*/\n"
	"		if((startID)==uint(0)){\n"
	"			cercelPosX.x=200.0;\n"
	"			cercelPosY.x=200.0;\n"
	"		}\n"
	"		else if((startID)==uint(1)){\n"
	"			cercelPosX.y=200.0;\n"
	"			cercelPosY.y=400.0;\n"
	"		}\n"
	"		else if((startID)==uint(3)){\n"
	"			cercelPosX.z=400.0;\n"
	"			cercelPosY.z=200.0;\n"
	"		}\n"
	"		else if((startID)==uint(4)){\n"
	"			cercelPosX.w=400.0;\n"
	"			cercelPosY.w=400.0;\n"
	"		}\n"
	"	}\n"
	"	flags=Flags;\n"
	"	color=inColor;\n"
	"\n"
	"}\n"
	;


/********************************************g_2DShape_fragmentshader***********************************************/
static const char* g_2DShape_fragmentshader = 
	"#version 330 core\n"
	"layout(location=0) out vec4 outcl;\n"
	"\n"
	"\n"
	"flat in uint color;\n"
	"flat in uint flags;\n"
	"\n"
	"in vec4 cercelPosX;\n"
	"in vec4 cercelPosY;\n"
	"in vec4 pos;\n"
	"\n"
	"/*flags bit structure\n"
	"	|0123|  -> Praticul\n"
	"	|4|     -> texture Enbled\n"
	"	|56789| -> texture slot\n"
	"	|10->31| ->reseved\n"
	"*/\n"
	"\n"
	"\n"
	"\n"
	"void main(){\n"
	"	float r = float((color>>24)&0xffu)/255.0;\n"
	"	float g = float((color>>16)&0xffu)/255.0;\n"
	"	float b = float((color>>8)&0xffu)/255.0;\n"
	"	float a = float(color&0xffu)/255.0;\n"
	"	\n"
	"	vec4 color;\n"
	"		\n"
	"	if( (flags) >= uint(1)){//it is a  cercul\n"
	"		\n"
	"		vec2 center = vec2((cercelPosX.x + cercelPosX.y)/2.0f , (cercelPosY.x + cercelPosY.y)/2.0f);//it all make sense, trust me bro\n"
	"		float raduce = cercelPosX.x- center.x;\n"
	"		float xVector = center.x - pos.x;\n"
	"		float yVector = center.y - pos.y;\n"
	"		if(xVector*xVector + yVector*yVector > raduce){\n"
	"			return;\n"
	"		}\n"
	"		\n"
	"	}\n"
	"	if( (flags & 0x10u) == uint(1)){// it is a texture\n"
	"		\n"
	"		return;	\n"
	"	}\n"
	"	\n"
	"	outcl =vec4(r,g,b,a);\n"
	"	\n"
	"}\n"
	;