static const char* g_2DShape_vertexshader = 
	"#version 330 core\n"
	"layout(location=0) in vec4 position;\n"
	"layout(location=1) in uint inColor;\n"
	"layout(location=2) in uint Flags;\n"
	"layout(location=3) in vec4 location3; // cneter of the cercul / texture \n"
	"// so , what ever tringel it passed; all what we will do is ortate it, whet ever position, to save the poor cpu frome some procesing cyculs\n"
	"\n"
	"//out pos;\n"
	"flat out uint color;\n"
	"flat out uint flags;\n"
	"\n"
	"out vec4 pos;\n"
	"\n"
	"uniform mat4 u_MVP;\n"
	"\n"
	"vec2 Rotate(vec2 pos,vec2 center,float theta){\n"
	"	float raduian=(theta*3.14159)/(180.0);\n"
	"	float X = pos.x-center.x;\n"
	"	float Y = pos.y-center.y;\n"
	"	float posx=center.x+X*cos(raduian)-Y*sin(raduian);\n"
	"	float posy=center.y+X*sin(raduian)+Y*cos(raduian);\n"
	"	return vec2(posx,posy);\n"
	"}\n"
	"\n"
	"\n"
	"void main(){\n"
	"	vec4 posi = position;\n"
	"	if( (Flags & 0xfu) == uint(1)){\n"
	"		posi= vec4(Rotate(position.xy,location3.xy,location3.z),position.zw); // the thread float of 'location3' will hold the theta\n"
	"	}\n"
	"	gl_Position=u_MVP*posi;\n"
	"	pos=posi;\n"
	"	\n"
	"	flags=Flags;\n"
	"	color=inColor;\n"
	"\n"
	"}\n"
	;


/********************************************g_2DShape_fragmentshader***********************************************/
static const char* g_2DShape_fragmentshader = 
	"#version 330 core\n"
	"layout(location=0) out vec4 outcl;\n"
	"\n"
	"\n"
	"flat in uint color;\n"
	"flat in uint flags;\n"
	"in vec4 pos;\n"
	"\n"
	"/*flags bit structure\n"
	"	|0123|  -> Praticul\n"
	"	|4|     -> texture Enbled\n"
	"	|56789| -> texture slot\n"
	"	|10->31| ->reseved\n"
	"*/\n"
	"\n"
	"\n"
	"\n"
	"void main(){\n"
	"	float r = float((color>>24)&0xffu)/255.0;\n"
	"	float g = float((color>>16)&0xffu)/255.0;\n"
	"	float b = float((color>>8)&0xffu)/255.0;\n"
	"	float a = float(color&0xffu)/255.0;\n"
	"	\n"
	"	\n"
	"	if( (flags & 0x10u) == uint(1)){// it is a texture\n"
	"		\n"
	"		return;	\n"
	"	}\n"
	"	\n"
	"	outcl =vec4(r,g,b,a);\n"
	"	\n"
	"}\n"
	;